FROM python:3.9-slim
WORKDIR /app
COPY . .
COPY requirement.txt .
RUN pip install --no-cache-dir -r  requirement.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]